org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1.2
android.useAndroidX=true
systemProp.https.protocols=TLSv1.2
systemProp.http.keepAlive=false
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=false
kotlin.incremental=false
org.gradle.java.home=D:\\DevKit\\Android\\AndroidStudio\\jbr
