const zh = {
  railViews: '页面、素材与图层',
  layers: '图层',
  topLayerFirst: '上层在前',
  dragLayerHint: '拖动调整图层顺序',
  emptyLayers: '当前跨页还没有元素',
  selectElement: '选择一个元素以调整布局',
  image: '图片',
  text: '文字',
  emptyImage: '空图片框',
  emptyText: '空文本',
  leftPage: '左页',
  rightPage: '右页',
  positionAndSize: '位置与尺寸',
  x: '水平位置',
  y: '垂直位置',
  width: '宽度',
  height: '高度',
  rotation: '旋转',
  resetRotation: '重置旋转',
  alignPage: '对齐页面',
  alignLeft: '对齐页面左边缘',
  alignHorizontalCenter: '在页面中水平居中',
  alignRight: '对齐页面右边缘',
  alignTop: '对齐页面上边缘',
  alignVerticalCenter: '在页面中垂直居中',
  alignBottom: '对齐页面下边缘',
  stack: '排列',
  bringToFront: '置于顶层',
  bringForward: '上移一层',
  sendBackward: '下移一层',
  sendToBack: '置于底层',
  duplicate: '创建副本',
  duplicateSpread: '复制跨页',
  lock: '锁定元素',
  unlock: '解锁元素',
  locked: '已锁定',
  unlockHint: '解锁后可调整内容与布局',
  crop: '裁剪图片',
  editText: '编辑文字',
  finishCropFirst: '完成裁剪后可调整布局',
  invalidNumber: '请输入有效数值',
  minimumSize: '最小尺寸为 5 mm',
} as const

type EditorCopy = { [Key in keyof typeof zh]: string }

const en: EditorCopy = {
  railViews: 'Pages, assets and layers',
  layers: 'Layers',
  topLayerFirst: 'Front to back',
  dragLayerHint: 'Drag to reorder layers',
  emptyLayers: 'No elements on this spread',
  selectElement: 'Select an element to adjust its layout',
  image: 'Image',
  text: 'Text',
  emptyImage: 'Empty image frame',
  emptyText: 'Empty text',
  leftPage: 'Left page',
  rightPage: 'Right page',
  positionAndSize: 'Position & size',
  x: 'Horizontal position',
  y: 'Vertical position',
  width: 'Width',
  height: 'Height',
  rotation: 'Rotation',
  resetRotation: 'Reset rotation',
  alignPage: 'Align to page',
  alignLeft: 'Align to left page edge',
  alignHorizontalCenter: 'Center horizontally on page',
  alignRight: 'Align to right page edge',
  alignTop: 'Align to top page edge',
  alignVerticalCenter: 'Center vertically on page',
  alignBottom: 'Align to bottom page edge',
  stack: 'Arrange',
  bringToFront: 'Bring to front',
  bringForward: 'Bring forward',
  sendBackward: 'Send backward',
  sendToBack: 'Send to back',
  duplicate: 'Duplicate',
  duplicateSpread: 'Duplicate spread',
  lock: 'Lock element',
  unlock: 'Unlock element',
  locked: 'Locked',
  unlockHint: 'Unlock to edit content and layout',
  crop: 'Crop image',
  editText: 'Edit text',
  finishCropFirst: 'Finish cropping to adjust layout',
  invalidNumber: 'Enter a valid number',
  minimumSize: 'Minimum size is 5 mm',
}

export function zineEditorCopy(language: 'zh' | 'en'): EditorCopy {
  return language === 'zh' ? zh : en
}
