export const localLibraryCopy = {
  zh: {
    title: '本地资源库', subtitle: '原始文件和索引集中存放在同一个资源库文件夹中',
    preparing: '正在读取本地资源库…', retry: '重试',
    welcomeTitle: '用你自己的文件夹管理照片',
    welcomeBody: '选择一个文件夹作为资源库。MO Gallery 会将原始文件、索引、预览缓存和资源库回收站统一保存在其中，便于整体迁移和备份。',
    create: '创建空资源库', createHint: '选择一个空文件夹并创建资源库',
    initialize: '初始化照片文件夹', initializeHint: '将已有照片文件夹初始化为资源库，不移动现有文件',
    open: '打开已有资源库', openHint: '打开包含 .mo-gallery 索引的文件夹',
    recent: '最近使用', noRecent: '还没有最近使用的资源库', unavailable: '位置不可用', removeRecent: '移除记录',
    allPhotos: '所有照片', favorites: '收藏', trash: '资源库回收站', folders: '文件夹', root: '资源库根目录',
    collections: '集合', tags: '标签', newCollection: '新建集合', newCollectionGroup: '新建集合组', newTag: '新建标签', renameCollection: '编辑集合', renameCollectionGroup: '编辑集合组', renameTag: '编辑标签',
    deleteCollection: '删除集合', deleteCollectionGroup: '删除集合组', deleteTag: '删除标签', organizationName: '名称', collectionParent: '所在集合组', collectionRoot: '未分组', tagColor: '标签颜色', noColor: '无颜色', noTags: '还没有标签', noCollections: '还没有集合',
    organizationSaved: '组织项已保存', organizationDeleted: '组织项已删除', deleteTagTitle: '删除这个标签？', deleteTagBody: '只会移除标签及其照片关系，不会删除照片文件。', deleteCollectionTitle: '删除这个集合？', deleteCollectionBody: '只会删除集合及其照片关系，不会删除照片文件。', deleteCollectionGroupTitle: '删除这个集合组？', deleteCollectionGroupBody: '集合组不是空的。确认后会连同其中的子组、集合和集合关系一起删除，但不会删除照片文件。', deleteEmptyCollectionGroupBody: '这个集合组为空。删除不会影响任何照片文件。', deleteGroupContents: '连同子集合删除', organizationUpdated: '照片组织已更新',
    batchEdit: '批量整理', selectedItems: '项已选', clearSelection: '清除选择', renameAsset: '重命名文件', moveAssetsToFolder: '移动到文件夹', assetFileName: '文件名', renameAssetTitle: '重命名照片文件', moveAssetsTitle: '移动照片到文件夹', assetMoveHint: '这会修改磁盘中的真实文件路径，但照片 ID、标签、集合和编辑信息保持不变。不会覆盖同名文件。', assetRenamed: '照片文件已重命名', assetsMoved: '照片已移动', assetsMovePartial: '部分照片移动失败', markFavorite: '设为收藏', unmarkFavorite: '取消收藏', add: '添加', remove: '移除', batchUpdated: '已更新选中照片',
    missingPhotos: '失联照片',
    search: '搜索文件名、路径、标题、备注、标签、集合或相机', import: '导入照片', close: '关闭资源库', switchLibrary: '切换资源库',
    scanning: '正在更新索引', scanPaused: '扫描已暂停', scanDone: '索引已是最新', scanFailed: '扫描失败', librarySuspended: '资源库磁盘已断开，正在等待重新连接', libraryIdentityMismatch: '重新连接的位置不是原资源库，请关闭后重新打开正确的资源库',
    pause: '暂停', resume: '继续', rescan: '重新扫描', cancel: '取消扫描',
    captured: '拍摄时间', discovered: '最近添加', name: '文件名', modified: '修改时间', size: '文件大小', rating: '评分', ascending: '升序', descending: '降序',
    filters: '筛选', clearFilters: '清除全部', filterLogicHint: '不同筛选项之间为“并且”，同一项多选为“或者”。', filterRating: '评分范围', filterColor: '颜色标记', filterFormat: '文件格式', filterPreview: '预览状态', filterCapturedDate: '拍摄日期', filterDiscoveredDate: '发现日期', filterCamera: '相机与镜头', filterCameraMake: '相机厂商（逗号分隔）', filterCameraModel: '相机型号（逗号分隔）', filterLens: '镜头（逗号分隔）', filterExposure: '曝光参数', filterAperture: '光圈', filterFocalLength: '焦距', filterOrientation: '画面方向', filterDimensions: '尺寸', filterWidth: '宽度', filterHeight: '高度', from: '从', to: '到', any: '不限', landscape: '横向', portrait: '纵向', square: '方形', red: '红', yellow: '黄', green: '绿', blue: '蓝', purple: '紫', preview_pending: '等待生成', preview_generating: '生成中', preview_ready: '可预览', preview_unavailable: '不可预览',
    empty: '当前视图没有照片', emptyHint: '可将照片拖放到这里，或选择“导入照片”。文件会按设置复制或移动到当前浏览的文件夹。',
    missingEmpty: '没有失联照片', missingEmptyHint: '扫描后未发现原文件缺失的照片。',
    loading: '正在加载照片…', loadMore: '加载更多', count: '项', incomplete: '扫描尚未完成，当前结果可能不完整',
    details: '照片信息', noSelection: '选择一张照片以查看信息', titleField: '标题', notes: '备注', favorite: '收藏', color: '颜色标记', save: '保存信息', saved: '信息已保存', autoSaving: '正在自动保存…', autoSaveHint: '修改后自动保存',
    originalPath: '资源库路径', dimensions: '尺寸', format: '格式', fileSize: '大小', openSystem: '使用默认程序打开', preview: '大图预览',
    moveToTrash: '移入资源库回收站', restore: '恢复到原位置', delete: '删除', deleteTitle: '如何删除这张照片？', trashedAssetTitle: '处理回收站中的照片', trashedAssetBody: '这张照片已经在资源库回收站中。恢复会把它放回原位置；永久删除无法撤销。', restoreTrashedAsset: '恢复照片', permanentTrashedAsset: '永久删除照片',
    deleteBody: '移入资源库回收站后可以恢复；永久删除会移除原始文件且无法撤销。', trashOption: '移入资源库回收站', permanentOption: '永久删除原文件',
    cancelAction: '取消', confirmPermanent: '永久删除', imported: '照片已导入资源库', importPartial: '部分文件无法导入资源库', importing: '正在导入照片…',
    importModeTitle: '首次导入时如何处理原文件？', importModeBody: '这个选择会保存为本地资源库的默认导入方式。此次取消不会导入文件，也不会保存默认值。',
    copyIntoLibrary: '复制到资源库', copyIntoLibraryHint: '保留原位置的文件，在资源库中创建一份受管理的副本。',
    moveIntoLibrary: '移动到资源库', moveIntoLibraryHint: '安全写入资源库后，从原位置移除文件。', importModeSettingsHint: '之后可在“系统设置 → 本地资源库”中修改。',
    drop: '松开以导入目标文件夹', externalDropLogicalRejected: '请先将文件导入真实文件夹，再把库内照片拖到集合、标签或收藏。', externalDropUnavailable: '此视图不能接收库外文件，请拖到资源库根目录或真实文件夹。', original: '原图', fitted: '适应窗口', generatingPreview: '正在生成预览…', unavailablePreview: '该格式已建立索引，但当前版本暂时无法生成预览', retryPreview: '重试预览', previewRetrySucceeded: '预览已重新生成', previewRetryFailed: '仍无法生成预览', previewFailureReason: '失败原因',
    rawHint: 'RAW 仅在能够提取内嵌预览图时显示缩略图', gifHint: 'GIF 在网格中显示静态首帧，在预览中播放动画',
    libraryLocation: '资源库位置', assets: '照片', missing: '失联', inTrash: '回收站',
    newFolder: '新增文件夹', renameFolder: '重命名', moveFolder: '移动到…', folderProperties: '属性', deleteFolder: '删除文件夹', folderName: '文件夹名称',
    createFolderTitle: '新建文件夹', createFolderPlaceholder: '输入文件夹名称', createAction: '创建', renameFolderTitle: '重命名文件夹', moveFolderTitle: '移动文件夹', destinationFolder: '目标文件夹', moveFolderHint: '文件夹和其中所有文件会移动到新位置，照片 ID、标签、集合和编辑信息保持不变。目标冲突时不会覆盖。', moveAction: '应用', folderMoved: '文件夹已移动', folderRenamed: '文件夹已重命名',
    folderPath: '资源库路径', folderPhotoCount: '照片数量', folderChildCount: '子文件夹数量', folderSize: '文件大小', folderModified: '修改时间',
    deleteFolderTitle: '删除文件夹', deleteFolderBody: '将「{name}」及其中的全部文件一起处理。请先核对下面的实际内容。', folderCreated: '文件夹已创建', folderDeleted: '文件夹已移入资源库回收站',
    folderDeleteCalculating: '正在统计文件夹内容…', managedAssets: '受管理资产', otherFiles: '其他文件', directoryCount: '目录数', totalSize: '总大小',
    moveFolderToTrash: '移入资源库回收站', moveFolderToTrashHint: '默认操作，可整批恢复这个文件夹。', permanentlyDeleteFolder: '永久删除文件夹', permanentFolderHint: '删除整个目录树，无法撤销。',
    folderPermanentConfirmTitle: '确认永久删除整个文件夹？', folderPermanentConfirmBody: '受管理资产、隐藏文件、不支持文件和未索引文件都会从磁盘删除，无法恢复。', back: '返回',
    folderTrashBatches: '文件夹回收批次', folderTrashEmpty: '没有文件夹回收批次', originalFolderPath: '原文件夹路径', trashedAt: '删除时间', restoreFolderBatch: '整批恢复', deleteFolderBatch: '整批永久删除',
    folderBatchHint: '这张照片属于文件夹回收批次；恢复或永久删除会处理整个文件夹。', restoreFolderBatchConfirm: '将整个文件夹恢复到原位置。', restoreDestination: '恢复到', originalParentMissing: '原父目录已不存在，请选择资源库内的其他位置。', restoreConflictHint: '如目标位置有同名文件夹，资源库不会覆盖；请修改文件夹名称后重试。', deleteFolderBatchConfirmTitle: '永久删除整个文件夹批次？', deleteFolderBatchConfirmBody: '该文件夹中的受管理资产和其他文件都会永久删除，无法恢复。',
    restoredFolder: '文件夹已恢复', permanentlyDeletedFolder: '文件夹已永久删除',
    cut: '剪切', copyAsset: '复制', uploadTo: '上传至', uploadPage: '上传页面', noAlbums: '暂无相册', loadingDestinations: '正在加载相册...',
    copiedToClipboard: '照片已复制到系统剪贴板', cutToClipboard: '照片已剪切到系统剪贴板', uploadPrepared: '已添加到上传页面',
    missingHint: '原文件不在资源库记录的路径。将文件放回完全相同的位置后可重新检查。', recheckMissing: '重新检查原文件', stillMissing: '原路径仍未找到文件', missingRestored: '原文件已恢复并重新纳入资源库',
    removeMissingRecord: '移除失联记录', removeMissingTitle: '移除这条失联记录？', removeMissingBody: '仅移除 MO Gallery 中的失联索引、标题、备注、评分等整理数据和缓存，不会删除磁盘文件。', missingRecordRemoved: '失联记录已移除',
    databaseBackups: '数据库备份', backupNow: '立即备份', backingUp: '正在备份…', noBackups: '还没有数据库备份', backupCreated: '数据库备份已创建', backupKindManual: '手动备份', backupKindDaily: '每日备份', backupKindUpgrade: '升级前备份', backupKindPreRestore: '恢复前备份',
    backupScopeHint: '这里只备份资源库索引与标题、标签、集合等整理数据，不包含照片原文件和预览缓存。', restoreBackup: '从此备份恢复', restoreBackupTitle: '确认恢复数据库？', restoreBackupBody: '当前索引和整理数据会替换为所选备份。恢复前会自动保存当前数据库；照片原文件不会被修改。', restoringBackup: '正在恢复…', backupRestored: '数据库已恢复', backupRestoreWarning: '恢复后资源库会重新扫描照片，以校准文件状态。',

  },
  en: {
    title: 'Local Library', subtitle: 'Originals and indexes stay together in one library folder',
    preparing: 'Reading local libraries...', retry: 'Try again',
    welcomeTitle: 'Keep photos in folders you control',
    welcomeBody: 'Choose a folder as a library. MO Gallery stores originals, indexes, preview cache, and the library trash together so the library can be moved as a unit.',
    create: 'Create empty library', createHint: 'Choose an empty folder and create a library',
    initialize: 'Initialize photo folder', initializeHint: 'Manage an existing photo folder without moving its files',
    open: 'Open existing library', openHint: 'Open a folder containing a .mo-gallery index',
    recent: 'Recent libraries', noRecent: 'No recent libraries yet', unavailable: 'Location unavailable', removeRecent: 'Remove entry',
    allPhotos: 'All photos', favorites: 'Favorites', missingPhotos: 'Missing photos', trash: 'Library trash', folders: 'Folders', root: 'Library root',
    collections: 'Collections', tags: 'Tags', newCollection: 'New collection', newCollectionGroup: 'New collection group', newTag: 'New tag', renameCollection: 'Edit collection', renameCollectionGroup: 'Edit collection group', renameTag: 'Edit tag',
    deleteCollection: 'Delete collection', deleteCollectionGroup: 'Delete collection group', deleteTag: 'Delete tag', organizationName: 'Name', collectionParent: 'Collection group', collectionRoot: 'Ungrouped', tagColor: 'Tag color', noColor: 'No color', noTags: 'No tags yet', noCollections: 'No collections yet',
    organizationSaved: 'Organization item saved', organizationDeleted: 'Organization item deleted', deleteTagTitle: 'Delete this tag?', deleteTagBody: 'This only removes the tag and its photo relationships. Photo files are not deleted.', deleteCollectionTitle: 'Delete this collection?', deleteCollectionBody: 'This only removes the collection and its photo relationships. Photo files are not deleted.', deleteCollectionGroupTitle: 'Delete this collection group?', deleteCollectionGroupBody: 'This group is not empty. Confirming also deletes its child groups, collections, and relationships, but never photo files.', deleteEmptyCollectionGroupBody: 'This group is empty. Deleting it does not affect photo files.', deleteGroupContents: 'Delete child collections', organizationUpdated: 'Photo organization updated',
    batchEdit: 'Batch organize', selectedItems: 'items selected', clearSelection: 'Clear selection', renameAsset: 'Rename file', moveAssetsToFolder: 'Move to folder', assetFileName: 'File name', renameAssetTitle: 'Rename photo file', moveAssetsTitle: 'Move photos to folder', assetMoveHint: 'This changes the real file path on disk while preserving the photo ID, tags, collections, and edits. Existing files are never overwritten.', assetRenamed: 'Photo file renamed', assetsMoved: 'Photos moved', assetsMovePartial: 'Some photos could not be moved', markFavorite: 'Mark favorite', unmarkFavorite: 'Remove favorite', add: 'Add', remove: 'Remove', batchUpdated: 'Selected photos updated',
    search: 'Search names, paths, notes, tags, collections, or camera', import: 'Import photos', close: 'Close library', switchLibrary: 'Switch library',
    scanning: 'Updating index', scanPaused: 'Scan paused', scanDone: 'Index is up to date', scanFailed: 'Scan failed', librarySuspended: 'Library storage disconnected; waiting for reconnection', libraryIdentityMismatch: 'The reconnected location is not the original library. Close it and reopen the correct library.',
    pause: 'Pause', resume: 'Resume', rescan: 'Rescan', cancel: 'Cancel scan',
    captured: 'Captured', discovered: 'Recently added', name: 'Filename', modified: 'Last modified', size: 'File size', rating: 'Rating', ascending: 'Ascending', descending: 'Descending',
    filters: 'Filters', clearFilters: 'Clear all', filterLogicHint: 'Different filters use AND; multiple choices in one filter use OR.', filterRating: 'Rating range', filterColor: 'Color label', filterFormat: 'File format', filterPreview: 'Preview status', filterCapturedDate: 'Captured date', filterDiscoveredDate: 'Discovered date', filterCamera: 'Camera and lens', filterCameraMake: 'Camera makes, comma-separated', filterCameraModel: 'Camera models, comma-separated', filterLens: 'Lenses, comma-separated', filterExposure: 'Exposure', filterAperture: 'Aperture', filterFocalLength: 'Focal length', filterOrientation: 'Orientation', filterDimensions: 'Dimensions', filterWidth: 'Width', filterHeight: 'Height', from: 'From', to: 'To', any: 'Any', landscape: 'Landscape', portrait: 'Portrait', square: 'Square', red: 'Red', yellow: 'Yellow', green: 'Green', blue: 'Blue', purple: 'Purple', preview_pending: 'Pending', preview_generating: 'Generating', preview_ready: 'Ready', preview_unavailable: 'Unavailable',
    empty: 'No photos in this view', emptyHint: 'Drop photos here or choose “Import photos”. Files will be copied or moved to the current folder according to your setting.',
    missingEmpty: 'No missing photos', missingEmptyHint: 'The scan found no photos whose original files are missing.',
    loading: 'Loading photos...', loadMore: 'Load more', count: 'items', incomplete: 'Scanning is not complete, so current results may be incomplete',
    details: 'Photo details', noSelection: 'Select a photo to inspect it', titleField: 'Title', notes: 'Notes', favorite: 'Favorite', color: 'Color label', save: 'Save details', saved: 'Details saved', autoSaving: 'Saving automatically...', autoSaveHint: 'Changes save automatically',
    originalPath: 'Library path', dimensions: 'Dimensions', format: 'Format', fileSize: 'Size', openSystem: 'Open in default app', preview: 'Large preview',
    moveToTrash: 'Move to library trash', restore: 'Restore to original location', delete: 'Delete', deleteTitle: 'How should this photo be deleted?', trashedAssetTitle: 'Handle photo in library trash', trashedAssetBody: 'This photo is already in library trash. Restore it to the original location, or permanently delete it. Permanent deletion cannot be undone.', restoreTrashedAsset: 'Restore photo', permanentTrashedAsset: 'Permanently delete photo',
    deleteBody: 'Library trash can be restored. Permanent deletion removes the original file and cannot be undone.', trashOption: 'Move to library trash', permanentOption: 'Permanently delete original',
    cancelAction: 'Cancel', confirmPermanent: 'Delete permanently', imported: 'Photos imported into the library', importPartial: 'Some files could not be imported into the library', importing: 'Importing photos...',
    importModeTitle: 'How should the first import handle source files?', importModeBody: 'This choice becomes the default local-library import mode. Cancelling imports nothing and saves no default.',
    copyIntoLibrary: 'Copy to library', copyIntoLibraryHint: 'Keep the source file and create a managed copy in the library.',
    moveIntoLibrary: 'Move to library', moveIntoLibraryHint: 'Remove the source only after it is safely written into the library.', importModeSettingsHint: 'You can change this later in Settings → Local Library.',
    drop: 'Release to import into the target folder', externalDropLogicalRejected: 'Import files into a real folder first, then drag library photos to a collection, tag, or Favorites.', externalDropUnavailable: 'This view cannot receive external files. Drop them on the library root or a real folder.', original: 'Original', fitted: 'Fit window', generatingPreview: 'Generating preview...', unavailablePreview: 'This format is indexed, but this version cannot generate a preview yet', retryPreview: 'Retry preview', previewRetrySucceeded: 'Preview regenerated', previewRetryFailed: 'Preview is still unavailable', previewFailureReason: 'Failure reason',
    rawHint: 'RAW thumbnails appear only when an embedded preview can be extracted', gifHint: 'GIFs use a static first frame in the grid and animate in preview',
    libraryLocation: 'Library location', assets: 'Photos', missing: 'Missing', inTrash: 'Trash',
    newFolder: 'New folder', renameFolder: 'Rename', moveFolder: 'Move to...', folderProperties: 'Properties', deleteFolder: 'Delete folder', folderName: 'Folder name',
    createFolderTitle: 'Create folder', createFolderPlaceholder: 'Enter a folder name', createAction: 'Create', renameFolderTitle: 'Rename folder', moveFolderTitle: 'Move folder', destinationFolder: 'Destination folder', moveFolderHint: 'The folder and its contents move together. Photo IDs, tags, collections, and edits are preserved. Existing targets are never overwritten.', moveAction: 'Apply', folderMoved: 'Folder moved', folderRenamed: 'Folder renamed',
    folderPath: 'Library path', folderPhotoCount: 'Photos', folderChildCount: 'Subfolders', folderSize: 'File size', folderModified: 'Modified',
    deleteFolderTitle: 'Delete folder', deleteFolderBody: 'Handle {name} and every file inside it. Review the actual contents below first.', folderCreated: 'Folder created', folderDeleted: 'Folder moved to library trash',
    folderDeleteCalculating: 'Calculating folder contents...', managedAssets: 'Managed assets', otherFiles: 'Other files', directoryCount: 'Folders', totalSize: 'Total size',
    moveFolderToTrash: 'Move folder to library trash', moveFolderToTrashHint: 'Default action. The whole folder can be restored.', permanentlyDeleteFolder: 'Permanently delete folder', permanentFolderHint: 'Deletes the whole directory tree and cannot be undone.',
    folderPermanentConfirmTitle: 'Permanently delete the whole folder?', folderPermanentConfirmBody: 'Managed assets, hidden files, unsupported files, and unindexed files will all be deleted from disk and cannot be recovered.', back: 'Back',
    folderTrashBatches: 'Trashed folder batches', folderTrashEmpty: 'No trashed folder batches', originalFolderPath: 'Original folder path', trashedAt: 'Deleted', restoreFolderBatch: 'Restore whole folder', deleteFolderBatch: 'Permanently delete whole folder',
    folderBatchHint: 'This photo belongs to a trashed folder batch. Restoring or permanently deleting it affects the whole folder.', restoreFolderBatchConfirm: 'The whole folder will be restored to its original location.', restoreDestination: 'Restore to', originalParentMissing: 'The original parent no longer exists. Choose another location inside the library.', restoreConflictHint: 'The library never overwrites an existing folder. Change the folder name if the target conflicts.', deleteFolderBatchConfirmTitle: 'Permanently delete this whole folder batch?', deleteFolderBatchConfirmBody: 'Managed assets and every other file in this folder will be permanently deleted and cannot be recovered.',
    restoredFolder: 'Folder restored', permanentlyDeletedFolder: 'Folder permanently deleted',
    cut: 'Cut', copyAsset: 'Copy', uploadTo: 'Upload to', uploadPage: 'Upload page', noAlbums: 'No albums', loadingDestinations: 'Loading albums...',
    copiedToClipboard: 'Photo copied to the system clipboard', cutToClipboard: 'Photo cut to the system clipboard', uploadPrepared: 'Added to the upload page',
    missingHint: 'The original file is no longer at its indexed library path. Put it back in exactly the same location, then recheck it.', recheckMissing: 'Recheck original file', stillMissing: 'The file is still missing from its original path', missingRestored: 'The original file was restored to the library',
    removeMissingRecord: 'Remove missing record', removeMissingTitle: 'Remove this missing record?', removeMissingBody: 'This removes the missing index record, organization data such as title, notes and rating, and cached previews from MO Gallery. It does not delete any disk file.', missingRecordRemoved: 'Missing record removed',
    databaseBackups: 'Database backups', backupNow: 'Back up now', backingUp: 'Backing up…', noBackups: 'No database backups yet', backupCreated: 'Database backup created', backupKindManual: 'Manual backup', backupKindDaily: 'Daily backup', backupKindUpgrade: 'Pre-upgrade backup', backupKindPreRestore: 'Pre-restore backup',
    backupScopeHint: 'This backs up the library index and organization data such as titles, tags, and collections. Photo originals and preview caches are not included.', restoreBackup: 'Restore this backup', restoreBackupTitle: 'Restore this database backup?', restoreBackupBody: 'The current index and organization data will be replaced by the selected backup. The current database is saved first; photo originals are not changed.', restoringBackup: 'Restoring…', backupRestored: 'Database restored', backupRestoreWarning: 'The library rescans photos after restoration to reconcile file state.',
  },
} as const

export type LocalLibraryLanguage = keyof typeof localLibraryCopy
export type LocalLibraryCopy = typeof localLibraryCopy[LocalLibraryLanguage]
