// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {types} from '../models';
import {config} from '../models';
import {image} from '../models';

export function AddPhotosToFilmRoll(arg1:string,arg2:Array<string>):Promise<services.FilmRollDTO>;

export function AddStoryPhoto(arg1:string,arg2:string):Promise<void>;

export function AppendEditorAiMessage(arg1:services.EditorAiMessageAppendInput):Promise<services.EditorAiMessageDTO>;

export function BatchDeletePhotos(arg1:services.BatchDeleteParams):Promise<services.BatchResult>;

export function BatchUpdateShowFlag(arg1:Array<string>,arg2:boolean):Promise<services.BatchResult>;

export function CheckDuplicates(arg1:Array<string>):Promise<services.DuplicateCheckResult>;

export function CleanupStorage(arg1:Array<string>,arg2:string):Promise<services.StorageCleanupResult>;

export function ClearEditorAiConversation(arg1:string):Promise<services.EditorAiConversationDTO>;

export function ClearLogs():Promise<void>;

export function CreateAlbum(arg1:services.CreateAlbumParams):Promise<services.AlbumDTO>;

export function CreateBlog(arg1:services.CreateBlogParams):Promise<services.BlogDTO>;

export function CreateEditorAiConversation(arg1:services.EditorAiConversationCreateInput):Promise<services.EditorAiConversationDTO>;

export function CreateFilmRoll(arg1:services.CreateFilmRollParams):Promise<services.FilmRollDTO>;

export function CreateFriend(arg1:services.CreateFriendParams):Promise<services.FriendDTO>;

export function CreateStorageSource(arg1:Record<string, string>):Promise<types.StorageSourceDTO>;

export function CreateStory(arg1:services.CreateStoryParams):Promise<services.StoryDTO>;

export function DeleteAlbum(arg1:string):Promise<void>;

export function DeleteBlog(arg1:string):Promise<void>;

export function DeleteComment(arg1:string):Promise<void>;

export function DeleteEditorAiConversation(arg1:string):Promise<void>;

export function DeleteFilmRoll(arg1:string):Promise<void>;

export function DeleteFriend(arg1:string):Promise<void>;

export function DeletePhoto(arg1:string,arg2:services.DeletePhotoParams):Promise<void>;

export function DeleteStorageSource(arg1:string):Promise<void>;

export function DeleteStory(arg1:string):Promise<void>;

export function DownloadMessageImageToLocal(arg1:string):Promise<string>;

export function FinishEditorAiMessage(arg1:services.EditorAiMessageFinishInput):Promise<services.EditorAiMessageDTO>;

export function FixMissingPhotos(arg1:Array<string>):Promise<services.FixMissingPhotosResult>;

export function GenerateThumbnail(arg1:string):Promise<services.PhotoDTO>;

export function GetAiConfig():Promise<config.AIConfig>;

export function GetAiHttpPort():Promise<number>;

export function GetAiImageDataURL(arg1:string):Promise<string>;

export function GetAlbum(arg1:string):Promise<services.AlbumDTO>;

export function GetAlbums():Promise<Array<services.AlbumDTO>>;

export function GetAllPhotos():Promise<Array<services.PhotoDTO>>;

export function GetApiConfig():Promise<Record<string, any>>;

export function GetBlog(arg1:string):Promise<services.BlogDTO>;

export function GetBlogs():Promise<Array<services.BlogDTO>>;

export function GetCameras():Promise<Array<services.CameraDTO>>;

export function GetCategories():Promise<Array<string>>;

export function GetComments(arg1:services.ListCommentsParams):Promise<services.PaginatedResponse_mo_gallery_desktop_services_CommentDTO_>;

export function GetEditorAiConversation(arg1:string):Promise<services.EditorAiConversationWithMessagesDTO>;

export function GetEditorAiConversations(arg1:string):Promise<Array<services.EditorAiConversationDTO>>;

export function GetFileThumbnail(arg1:string):Promise<string>;

export function GetFilmRoll(arg1:string):Promise<services.FilmRollDTO>;

export function GetFilmRolls():Promise<Array<services.FilmRollDTO>>;

export function GetFriends():Promise<Array<services.FriendDTO>>;

export function GetLenses():Promise<Array<services.LensDTO>>;

export function GetLinuxDoAuthUrl():Promise<services.LinuxDoAuthUrlDTO>;

export function GetLinuxDoBinding():Promise<services.LinuxDoBindingDTO>;

export function GetLogConfig():Promise<Record<string, any>>;

export function GetLogDir():Promise<string>;

export function GetLogStats():Promise<Record<string, any>>;

export function GetLogs(arg1:string,arg2:string,arg3:number):Promise<Array<services.LogEntry>>;

export function GetOverview():Promise<services.OverviewDTO>;

export function GetPhoto(arg1:string):Promise<services.PhotoDTO>;

export function GetPhotos(arg1:services.ListPhotosParams):Promise<services.PaginatedResponse_mo_gallery_desktop_services_PhotoDTO_>;

export function GetSettings():Promise<Record<string, string>>;

export function GetStorageSources():Promise<Array<types.StorageSourceDTO>>;

export function GetStories():Promise<Array<services.StoryDTO>>;

export function GetStory(arg1:string):Promise<services.StoryDTO>;

export function GetStoryAiModels():Promise<services.StoryAiModelsResponseDTO>;

export function GetStoryAiProviderModels(arg1:string):Promise<services.StoryAiModelsResponseDTO>;

export function GetZineCJKFontInfo():Promise<services.ZineCJKFontInfo>;

export function GetZineImageDataURL(arg1:string):Promise<string>;

export function IsLinuxDoEnabled():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<services.LoginResult>;

export function OpenLogDir():Promise<void>;

export function PrepareUpload(arg1:Array<string>):Promise<Array<services.PreparedFile>>;

export function RemovePhotoFromFilmRoll(arg1:string,arg2:string):Promise<services.FilmRollDTO>;

export function RemoveStoryPhoto(arg1:string,arg2:string):Promise<void>;

export function ReorderFilmRollFrames(arg1:string):Promise<services.FilmRollDTO>;

export function ReorderStoryPhotos(arg1:string,arg2:Array<string>):Promise<services.StoryDTO>;

export function SaveAiImageToAlbum(arg1:string):Promise<services.PhotoDTO>;

export function SaveMessageImageToAlbum(arg1:string,arg2:string):Promise<services.PhotoDTO>;

export function ScanStorage(arg1:services.StorageScanParams):Promise<services.StorageScanResult>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SetAuth(arg1:string,arg2:string):Promise<services.UserInfo>;

export function ToggleFeatured(arg1:string):Promise<services.PhotoDTO>;

export function ToggleShowFlag(arg1:string):Promise<services.PhotoDTO>;

export function UnbindLinuxDoAccount():Promise<void>;

export function UpdateAiConfig(arg1:config.AIConfig):Promise<void>;

export function UpdateAlbum(arg1:string,arg2:services.UpdateAlbumParams):Promise<services.AlbumDTO>;

export function UpdateBlog(arg1:string,arg2:services.UpdateBlogParams):Promise<services.BlogDTO>;

export function UpdateCommentStatus(arg1:string,arg2:string):Promise<void>;

export function UpdateEditorAiConversation(arg1:string,arg2:services.EditorAiConversationUpdateInput):Promise<services.EditorAiConversationDTO>;

export function UpdateEditorAiTaskState(arg1:services.EditorAiTaskStateUpdateInput):Promise<services.EditorAiMessageDTO>;

export function UpdateFilmRoll(arg1:string,arg2:services.UpdateFilmRollParams):Promise<services.FilmRollDTO>;

export function UpdateFriend(arg1:string,arg2:services.UpdateFriendParams):Promise<services.FriendDTO>;

export function UpdateLogConfig(arg1:Record<string, any>):Promise<void>;

export function UpdatePhoto(arg1:string,arg2:services.UpdatePhotoParams):Promise<services.PhotoDTO>;

export function UpdateSettings(arg1:Record<string, string>):Promise<Record<string, string>>;

export function UpdateStorageSource(arg1:string,arg2:Record<string, string>):Promise<types.StorageSourceDTO>;

export function UpdateStory(arg1:string,arg2:services.UpdateStoryParams):Promise<services.StoryDTO>;

export function UploadFile(arg1:string,arg2:services.UploadSettings,arg3:string,arg4:image.ExifData):Promise<services.UploadResult>;

export function ValidateToken(arg1:string):Promise<services.UserInfo>;
