// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPhotosToAlbum(arg1, arg2) {
  return window['go']['main']['App']['AddPhotosToAlbum'](arg1, arg2);
}

export function AddPhotosToFilmRoll(arg1, arg2) {
  return window['go']['main']['App']['AddPhotosToFilmRoll'](arg1, arg2);
}

export function AddStoryPhoto(arg1, arg2) {
  return window['go']['main']['App']['AddStoryPhoto'](arg1, arg2);
}

export function AppendEditorAiMessage(arg1) {
  return window['go']['main']['App']['AppendEditorAiMessage'](arg1);
}

export function AppendZineLogs(arg1) {
  return window['go']['main']['App']['AppendZineLogs'](arg1);
}

export function BatchDeletePhotos(arg1) {
  return window['go']['main']['App']['BatchDeletePhotos'](arg1);
}

export function BatchUpdateLocalAssetOrganization(arg1) {
  return window['go']['main']['App']['BatchUpdateLocalAssetOrganization'](arg1);
}

export function BatchUpdateLocalAssetOrganizationByQuery(arg1, arg2) {
  return window['go']['main']['App']['BatchUpdateLocalAssetOrganizationByQuery'](arg1, arg2);
}

export function BatchUpdateShowFlag(arg1, arg2) {
  return window['go']['main']['App']['BatchUpdateShowFlag'](arg1, arg2);
}

export function CallAgentMCPTool(arg1) {
  return window['go']['main']['App']['CallAgentMCPTool'](arg1);
}

export function CancelAgentMCPTool(arg1) {
  return window['go']['main']['App']['CancelAgentMCPTool'](arg1);
}

export function CancelLocalLibraryScan() {
  return window['go']['main']['App']['CancelLocalLibraryScan']();
}

export function CheckCloudDownloadConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckCloudDownloadConflict'](arg1, arg2, arg3);
}

export function CheckCloudDownloadConflictByFileName(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckCloudDownloadConflictByFileName'](arg1, arg2, arg3);
}

export function CheckDuplicates(arg1) {
  return window['go']['main']['App']['CheckDuplicates'](arg1);
}

export function CheckForUpdates(arg1, arg2) {
  return window['go']['main']['App']['CheckForUpdates'](arg1, arg2);
}

export function CheckLocalLibraryUpgrade(arg1) {
  return window['go']['main']['App']['CheckLocalLibraryUpgrade'](arg1);
}

export function CleanupStorage(arg1, arg2) {
  return window['go']['main']['App']['CleanupStorage'](arg1, arg2);
}

export function ClearAuth() {
  return window['go']['main']['App']['ClearAuth']();
}

export function ClearEditorAiConversation(arg1) {
  return window['go']['main']['App']['ClearEditorAiConversation'](arg1);
}

export function ClearLocalAssetCloudLink(arg1) {
  return window['go']['main']['App']['ClearLocalAssetCloudLink'](arg1);
}

export function ClearLocalLibraryPreviewCache() {
  return window['go']['main']['App']['ClearLocalLibraryPreviewCache']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseLocalLibrary() {
  return window['go']['main']['App']['CloseLocalLibrary']();
}

export function CompleteSetup(arg1) {
  return window['go']['main']['App']['CompleteSetup'](arg1);
}

export function CopyLocalAssetsToClipboard(arg1, arg2) {
  return window['go']['main']['App']['CopyLocalAssetsToClipboard'](arg1, arg2);
}

export function CreateAlbum(arg1) {
  return window['go']['main']['App']['CreateAlbum'](arg1);
}

export function CreateBlog(arg1) {
  return window['go']['main']['App']['CreateBlog'](arg1);
}

export function CreateDesktopStorageSource(arg1) {
  return window['go']['main']['App']['CreateDesktopStorageSource'](arg1);
}

export function CreateEditorAiConversation(arg1) {
  return window['go']['main']['App']['CreateEditorAiConversation'](arg1);
}

export function CreateFilmRoll(arg1) {
  return window['go']['main']['App']['CreateFilmRoll'](arg1);
}

export function CreateFriend(arg1) {
  return window['go']['main']['App']['CreateFriend'](arg1);
}

export function CreateLocalAssetQueryToken(arg1) {
  return window['go']['main']['App']['CreateLocalAssetQueryToken'](arg1);
}

export function CreateLocalLibrary(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalLibrary'](arg1, arg2);
}

export function CreateLocalLibraryBackup() {
  return window['go']['main']['App']['CreateLocalLibraryBackup']();
}

export function CreateLocalLibraryCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLocalLibraryCollection'](arg1, arg2, arg3);
}

export function CreateLocalLibraryFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalLibraryFolder'](arg1, arg2);
}

export function CreateLocalLibraryTag(arg1, arg2) {
  return window['go']['main']['App']['CreateLocalLibraryTag'](arg1, arg2);
}

export function CreateStory(arg1) {
  return window['go']['main']['App']['CreateStory'](arg1);
}

export function DeleteAlbum(arg1) {
  return window['go']['main']['App']['DeleteAlbum'](arg1);
}

export function DeleteBlog(arg1) {
  return window['go']['main']['App']['DeleteBlog'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['App']['DeleteComment'](arg1);
}

export function DeleteDesktopStorageSource(arg1) {
  return window['go']['main']['App']['DeleteDesktopStorageSource'](arg1);
}

export function DeleteEditorAiConversation(arg1) {
  return window['go']['main']['App']['DeleteEditorAiConversation'](arg1);
}

export function DeleteFilmRoll(arg1) {
  return window['go']['main']['App']['DeleteFilmRoll'](arg1);
}

export function DeleteFriend(arg1) {
  return window['go']['main']['App']['DeleteFriend'](arg1);
}

export function DeleteLocalAssetCloud(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocalAssetCloud'](arg1, arg2);
}

export function DeleteLocalAssetCloudAndLocal(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocalAssetCloudAndLocal'](arg1, arg2);
}

export function DeleteLocalDraft(arg1) {
  return window['go']['main']['App']['DeleteLocalDraft'](arg1);
}

export function DeleteLocalLibraryCollection(arg1) {
  return window['go']['main']['App']['DeleteLocalLibraryCollection'](arg1);
}

export function DeleteLocalLibraryCollectionGroup(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocalLibraryCollectionGroup'](arg1, arg2);
}

export function DeleteLocalLibraryFolder(arg1) {
  return window['go']['main']['App']['DeleteLocalLibraryFolder'](arg1);
}

export function DeleteLocalLibraryTag(arg1) {
  return window['go']['main']['App']['DeleteLocalLibraryTag'](arg1);
}

export function DeletePhoto(arg1, arg2) {
  return window['go']['main']['App']['DeletePhoto'](arg1, arg2);
}

export function DeleteStory(arg1) {
  return window['go']['main']['App']['DeleteStory'](arg1);
}

export function DeleteZineProject(arg1) {
  return window['go']['main']['App']['DeleteZineProject'](arg1);
}

export function DiscoverAgentMCPServerTools(arg1) {
  return window['go']['main']['App']['DiscoverAgentMCPServerTools'](arg1);
}

export function DownloadCloudPhotoToFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadCloudPhotoToFolder'](arg1, arg2, arg3);
}

export function DownloadCloudPhotoToLocalLibrary(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadCloudPhotoToLocalLibrary'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadMessageImageToLocal(arg1) {
  return window['go']['main']['App']['DownloadMessageImageToLocal'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExecuteLocalAssetMovePlan(arg1) {
  return window['go']['main']['App']['ExecuteLocalAssetMovePlan'](arg1);
}

export function ExecuteLocalLibraryFolderMovePlan(arg1) {
  return window['go']['main']['App']['ExecuteLocalLibraryFolderMovePlan'](arg1);
}

export function FetchURLMetadata(arg1) {
  return window['go']['main']['App']['FetchURLMetadata'](arg1);
}

export function FinishEditorAiMessage(arg1) {
  return window['go']['main']['App']['FinishEditorAiMessage'](arg1);
}

export function FixMissingPhotos(arg1) {
  return window['go']['main']['App']['FixMissingPhotos'](arg1);
}

export function GenerateThumbnail(arg1) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1);
}

export function GetAgentExtensionSnapshot() {
  return window['go']['main']['App']['GetAgentExtensionSnapshot']();
}

export function GetAiConfig() {
  return window['go']['main']['App']['GetAiConfig']();
}

export function GetAiHttpPort() {
  return window['go']['main']['App']['GetAiHttpPort']();
}

export function GetAiImageDataURL(arg1) {
  return window['go']['main']['App']['GetAiImageDataURL'](arg1);
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetAlbums() {
  return window['go']['main']['App']['GetAlbums']();
}

export function GetAllPhotos() {
  return window['go']['main']['App']['GetAllPhotos']();
}

export function GetApiConfig() {
  return window['go']['main']['App']['GetApiConfig']();
}

export function GetBlog(arg1) {
  return window['go']['main']['App']['GetBlog'](arg1);
}

export function GetBlogs() {
  return window['go']['main']['App']['GetBlogs']();
}

export function GetCameras() {
  return window['go']['main']['App']['GetCameras']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetComments(arg1) {
  return window['go']['main']['App']['GetComments'](arg1);
}

export function GetDesktopPluginMarketplace(arg1) {
  return window['go']['main']['App']['GetDesktopPluginMarketplace'](arg1);
}

export function GetDesktopStoragePlugins() {
  return window['go']['main']['App']['GetDesktopStoragePlugins']();
}

export function GetDesktopStorageSourceCredentials(arg1) {
  return window['go']['main']['App']['GetDesktopStorageSourceCredentials'](arg1);
}

export function GetDesktopStorageSources() {
  return window['go']['main']['App']['GetDesktopStorageSources']();
}

export function GetDesktopSystemPlugins() {
  return window['go']['main']['App']['GetDesktopSystemPlugins']();
}

export function GetEditorAiConversation(arg1) {
  return window['go']['main']['App']['GetEditorAiConversation'](arg1);
}

export function GetEditorAiConversationMessagesPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetEditorAiConversationMessagesPage'](arg1, arg2, arg3, arg4);
}

export function GetEditorAiConversationPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEditorAiConversationPage'](arg1, arg2, arg3);
}

export function GetEditorAiConversations(arg1) {
  return window['go']['main']['App']['GetEditorAiConversations'](arg1);
}

export function GetFileThumbnail(arg1) {
  return window['go']['main']['App']['GetFileThumbnail'](arg1);
}

export function GetFilmRoll(arg1) {
  return window['go']['main']['App']['GetFilmRoll'](arg1);
}

export function GetFilmRolls() {
  return window['go']['main']['App']['GetFilmRolls']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetLenses() {
  return window['go']['main']['App']['GetLenses']();
}

export function GetLinuxDoAuthUrl() {
  return window['go']['main']['App']['GetLinuxDoAuthUrl']();
}

export function GetLinuxDoBinding() {
  return window['go']['main']['App']['GetLinuxDoBinding']();
}

export function GetLocalAssetOriginalPaths(arg1) {
  return window['go']['main']['App']['GetLocalAssetOriginalPaths'](arg1);
}

export function GetLocalDraft(arg1) {
  return window['go']['main']['App']['GetLocalDraft'](arg1);
}

export function GetLocalLibraryBackups() {
  return window['go']['main']['App']['GetLocalLibraryBackups']();
}

export function GetLocalLibraryCacheStats() {
  return window['go']['main']['App']['GetLocalLibraryCacheStats']();
}

export function GetLocalLibraryEntryState() {
  return window['go']['main']['App']['GetLocalLibraryEntryState']();
}

export function GetLocalLibraryFolderProperties(arg1) {
  return window['go']['main']['App']['GetLocalLibraryFolderProperties'](arg1);
}

export function GetLocalLibraryPreferences() {
  return window['go']['main']['App']['GetLocalLibraryPreferences']();
}

export function GetLocalLibrarySnapshot() {
  return window['go']['main']['App']['GetLocalLibrarySnapshot']();
}

export function GetLogConfig() {
  return window['go']['main']['App']['GetLogConfig']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetLogStats() {
  return window['go']['main']['App']['GetLogStats']();
}

export function GetLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3);
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetPhoto(arg1) {
  return window['go']['main']['App']['GetPhoto'](arg1);
}

export function GetPhotos(arg1) {
  return window['go']['main']['App']['GetPhotos'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSetupState() {
  return window['go']['main']['App']['GetSetupState']();
}

export function GetStorageSources() {
  return window['go']['main']['App']['GetStorageSources']();
}

export function GetStories() {
  return window['go']['main']['App']['GetStories']();
}

export function GetStory(arg1) {
  return window['go']['main']['App']['GetStory'](arg1);
}

export function GetStoryAiModels() {
  return window['go']['main']['App']['GetStoryAiModels']();
}

export function GetStoryAiProviderModels(arg1) {
  return window['go']['main']['App']['GetStoryAiProviderModels'](arg1);
}

export function GetWindowAppearance() {
  return window['go']['main']['App']['GetWindowAppearance']();
}

export function GetZineAssetBlob(arg1) {
  return window['go']['main']['App']['GetZineAssetBlob'](arg1);
}

export function GetZineCJKFontInfo() {
  return window['go']['main']['App']['GetZineCJKFontInfo']();
}

export function GetZineImageDataURL(arg1) {
  return window['go']['main']['App']['GetZineImageDataURL'](arg1);
}

export function GetZineLogPath() {
  return window['go']['main']['App']['GetZineLogPath']();
}

export function GetZineProject(arg1) {
  return window['go']['main']['App']['GetZineProject'](arg1);
}

export function GetZineSystemFonts() {
  return window['go']['main']['App']['GetZineSystemFonts']();
}

export function ImportAgentMCPServers(arg1) {
  return window['go']['main']['App']['ImportAgentMCPServers'](arg1);
}

export function ImportLocalLibraryFiles(arg1, arg2) {
  return window['go']['main']['App']['ImportLocalLibraryFiles'](arg1, arg2);
}

export function InitializeLocalLibrary(arg1, arg2) {
  return window['go']['main']['App']['InitializeLocalLibrary'](arg1, arg2);
}

export function InstallDesktopMarketplacePlugin(arg1, arg2) {
  return window['go']['main']['App']['InstallDesktopMarketplacePlugin'](arg1, arg2);
}

export function InstallDesktopStoragePlugin(arg1) {
  return window['go']['main']['App']['InstallDesktopStoragePlugin'](arg1);
}

export function InstallDesktopStoragePluginPackage(arg1) {
  return window['go']['main']['App']['InstallDesktopStoragePluginPackage'](arg1);
}

export function InstallDesktopSystemPlugin(arg1) {
  return window['go']['main']['App']['InstallDesktopSystemPlugin'](arg1);
}

export function InstallDesktopSystemPluginPackage(arg1) {
  return window['go']['main']['App']['InstallDesktopSystemPluginPackage'](arg1);
}

export function IsLinuxDoEnabled() {
  return window['go']['main']['App']['IsLinuxDoEnabled']();
}

export function ListDesktopStorageObjects(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListDesktopStorageObjects'](arg1, arg2, arg3, arg4);
}

export function ListDesktopStoragePluginVersions(arg1) {
  return window['go']['main']['App']['ListDesktopStoragePluginVersions'](arg1);
}

export function ListDesktopSystemPluginVersions(arg1) {
  return window['go']['main']['App']['ListDesktopSystemPluginVersions'](arg1);
}

export function ListLocalAssets(arg1) {
  return window['go']['main']['App']['ListLocalAssets'](arg1);
}

export function ListLocalDrafts() {
  return window['go']['main']['App']['ListLocalDrafts']();
}

export function ListLocalFolders() {
  return window['go']['main']['App']['ListLocalFolders']();
}

export function ListLocalLibraryCollectionGroups() {
  return window['go']['main']['App']['ListLocalLibraryCollectionGroups']();
}

export function ListLocalLibraryCollections() {
  return window['go']['main']['App']['ListLocalLibraryCollections']();
}

export function ListLocalLibraryTags() {
  return window['go']['main']['App']['ListLocalLibraryTags']();
}

export function ListLocalLibraryTrashedFolders() {
  return window['go']['main']['App']['ListLocalLibraryTrashedFolders']();
}

export function ListZineProjects() {
  return window['go']['main']['App']['ListZineProjects']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function MoveDesktopPluginPhotos(arg1) {
  return window['go']['main']['App']['MoveDesktopPluginPhotos'](arg1);
}

export function MoveLocalAssets(arg1, arg2) {
  return window['go']['main']['App']['MoveLocalAssets'](arg1, arg2);
}

export function MoveLocalLibraryFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveLocalLibraryFolder'](arg1, arg2, arg3);
}

export function OpenDesktopStoragePluginLocation(arg1) {
  return window['go']['main']['App']['OpenDesktopStoragePluginLocation'](arg1);
}

export function OpenDesktopSystemPluginLocation(arg1) {
  return window['go']['main']['App']['OpenDesktopSystemPluginLocation'](arg1);
}

export function OpenDownloadedUpdate() {
  return window['go']['main']['App']['OpenDownloadedUpdate']();
}

export function OpenLocalAssetInDefaultApp(arg1) {
  return window['go']['main']['App']['OpenLocalAssetInDefaultApp'](arg1);
}

export function OpenLocalAssetInFileManager(arg1) {
  return window['go']['main']['App']['OpenLocalAssetInFileManager'](arg1);
}

export function OpenLocalLibrary(arg1) {
  return window['go']['main']['App']['OpenLocalLibrary'](arg1);
}

export function OpenLocalLibraryFolderInFileManager(arg1) {
  return window['go']['main']['App']['OpenLocalLibraryFolderInFileManager'](arg1);
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PauseLocalLibraryScan() {
  return window['go']['main']['App']['PauseLocalLibraryScan']();
}

export function PermanentDeleteActiveLocalLibraryFolder(arg1) {
  return window['go']['main']['App']['PermanentDeleteActiveLocalLibraryFolder'](arg1);
}

export function PermanentDeleteLocalAssets(arg1) {
  return window['go']['main']['App']['PermanentDeleteLocalAssets'](arg1);
}

export function PermanentDeleteLocalLibraryFolder(arg1) {
  return window['go']['main']['App']['PermanentDeleteLocalLibraryFolder'](arg1);
}

export function PlanLocalAssetMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlanLocalAssetMove'](arg1, arg2, arg3);
}

export function PlanLocalLibraryFolderMove(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlanLocalLibraryFolderMove'](arg1, arg2, arg3, arg4);
}

export function PrepareClipboardUpload(arg1, arg2) {
  return window['go']['main']['App']['PrepareClipboardUpload'](arg1, arg2);
}

export function PrepareLocalAssetUpload(arg1) {
  return window['go']['main']['App']['PrepareLocalAssetUpload'](arg1);
}

export function PrepareUpload(arg1) {
  return window['go']['main']['App']['PrepareUpload'](arg1);
}

export function PreviewLocalLibraryFolderDeletion(arg1) {
  return window['go']['main']['App']['PreviewLocalLibraryFolderDeletion'](arg1);
}

export function ReadAgentSkill(arg1) {
  return window['go']['main']['App']['ReadAgentSkill'](arg1);
}

export function ReadAgentSkillResource(arg1, arg2) {
  return window['go']['main']['App']['ReadAgentSkillResource'](arg1, arg2);
}

export function RebuildLocalLibraryThumbnails(arg1) {
  return window['go']['main']['App']['RebuildLocalLibraryThumbnails'](arg1);
}

export function RecheckMissingLocalAssets(arg1) {
  return window['go']['main']['App']['RecheckMissingLocalAssets'](arg1);
}

export function RemoveAgentMCPServer(arg1) {
  return window['go']['main']['App']['RemoveAgentMCPServer'](arg1);
}

export function RemoveAgentSkill(arg1) {
  return window['go']['main']['App']['RemoveAgentSkill'](arg1);
}

export function RemoveMissingLocalAssets(arg1) {
  return window['go']['main']['App']['RemoveMissingLocalAssets'](arg1);
}

export function RemovePhotoFromAlbum(arg1, arg2) {
  return window['go']['main']['App']['RemovePhotoFromAlbum'](arg1, arg2);
}

export function RemovePhotoFromFilmRoll(arg1, arg2) {
  return window['go']['main']['App']['RemovePhotoFromFilmRoll'](arg1, arg2);
}

export function RemoveRecentLocalLibrary(arg1) {
  return window['go']['main']['App']['RemoveRecentLocalLibrary'](arg1);
}

export function RemoveStoryPhoto(arg1, arg2) {
  return window['go']['main']['App']['RemoveStoryPhoto'](arg1, arg2);
}

export function RenameLocalAsset(arg1, arg2) {
  return window['go']['main']['App']['RenameLocalAsset'](arg1, arg2);
}

export function ReorderFilmRollFrames(arg1) {
  return window['go']['main']['App']['ReorderFilmRollFrames'](arg1);
}

export function ReorderFriends(arg1) {
  return window['go']['main']['App']['ReorderFriends'](arg1);
}

export function ReorderStoryPhotos(arg1, arg2) {
  return window['go']['main']['App']['ReorderStoryPhotos'](arg1, arg2);
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function RestoreLocalAsset(arg1) {
  return window['go']['main']['App']['RestoreLocalAsset'](arg1);
}

export function RestoreLocalLibraryBackup(arg1) {
  return window['go']['main']['App']['RestoreLocalLibraryBackup'](arg1);
}

export function RestoreLocalLibraryFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreLocalLibraryFolder'](arg1, arg2, arg3);
}

export function ResumeLocalLibraryScan() {
  return window['go']['main']['App']['ResumeLocalLibraryScan']();
}

export function RetryLocalAssetPreviews(arg1) {
  return window['go']['main']['App']['RetryLocalAssetPreviews'](arg1);
}

export function RevokeAgentAuthorization(arg1) {
  return window['go']['main']['App']['RevokeAgentAuthorization'](arg1);
}

export function RollbackDesktopStoragePlugin(arg1, arg2) {
  return window['go']['main']['App']['RollbackDesktopStoragePlugin'](arg1, arg2);
}

export function RollbackDesktopSystemPlugin(arg1, arg2) {
  return window['go']['main']['App']['RollbackDesktopSystemPlugin'](arg1, arg2);
}

export function SaveAgentMCPServer(arg1) {
  return window['go']['main']['App']['SaveAgentMCPServer'](arg1);
}

export function SaveAiImageToAlbum(arg1) {
  return window['go']['main']['App']['SaveAiImageToAlbum'](arg1);
}

export function SaveLocalDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveLocalDraft'](arg1, arg2);
}

export function SaveMessageImageToAlbum(arg1, arg2) {
  return window['go']['main']['App']['SaveMessageImageToAlbum'](arg1, arg2);
}

export function SaveMessageImageToLocalLibrary(arg1, arg2) {
  return window['go']['main']['App']['SaveMessageImageToLocalLibrary'](arg1, arg2);
}

export function SaveZineAssetBlob(arg1, arg2) {
  return window['go']['main']['App']['SaveZineAssetBlob'](arg1, arg2);
}

export function SaveZineProject(arg1) {
  return window['go']['main']['App']['SaveZineProject'](arg1);
}

export function ScanStorage(arg1) {
  return window['go']['main']['App']['ScanStorage'](arg1);
}

export function SelectAndImportSkillArchive() {
  return window['go']['main']['App']['SelectAndImportSkillArchive']();
}

export function SelectAndImportSkillDirectory() {
  return window['go']['main']['App']['SelectAndImportSkillDirectory']();
}

export function SelectDesktopStoragePluginManifest() {
  return window['go']['main']['App']['SelectDesktopStoragePluginManifest']();
}

export function SelectDesktopStoragePluginPackage() {
  return window['go']['main']['App']['SelectDesktopStoragePluginPackage']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectLocalLibraryFolder(arg1) {
  return window['go']['main']['App']['SelectLocalLibraryFolder'](arg1);
}

export function SelectLocalLibraryImportFiles() {
  return window['go']['main']['App']['SelectLocalLibraryImportFiles']();
}

export function SetAgentMCPServerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentMCPServerEnabled'](arg1, arg2);
}

export function SetAgentSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentSkillEnabled'](arg1, arg2);
}

export function SetAgentSkillScriptExecution(arg1, arg2) {
  return window['go']['main']['App']['SetAgentSkillScriptExecution'](arg1, arg2);
}

export function SetAlbumCover(arg1, arg2) {
  return window['go']['main']['App']['SetAlbumCover'](arg1, arg2);
}

export function SetAuth(arg1, arg2) {
  return window['go']['main']['App']['SetAuth'](arg1, arg2);
}

export function SetDesktopStorageSourceEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetDesktopStorageSourceEnabled'](arg1, arg2);
}

export function SetFilmRollFrameOrder(arg1, arg2) {
  return window['go']['main']['App']['SetFilmRollFrameOrder'](arg1, arg2);
}

export function SetLocalAssetCloudLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLocalAssetCloudLink'](arg1, arg2, arg3);
}

export function SetLocalAssetCollections(arg1, arg2) {
  return window['go']['main']['App']['SetLocalAssetCollections'](arg1, arg2);
}

export function SetLocalAssetTags(arg1, arg2) {
  return window['go']['main']['App']['SetLocalAssetTags'](arg1, arg2);
}

export function SetLocalLibraryImportMode(arg1) {
  return window['go']['main']['App']['SetLocalLibraryImportMode'](arg1);
}

export function StartLocalLibraryScan() {
  return window['go']['main']['App']['StartLocalLibraryScan']();
}

export function SyncLocalLibraryCloud() {
  return window['go']['main']['App']['SyncLocalLibraryCloud']();
}

export function TestAgentMCPServer(arg1) {
  return window['go']['main']['App']['TestAgentMCPServer'](arg1);
}

export function TestDesktopStorageSource(arg1) {
  return window['go']['main']['App']['TestDesktopStorageSource'](arg1);
}

export function ToggleFeatured(arg1) {
  return window['go']['main']['App']['ToggleFeatured'](arg1);
}

export function ToggleShowFlag(arg1) {
  return window['go']['main']['App']['ToggleShowFlag'](arg1);
}

export function TrashLocalAssets(arg1) {
  return window['go']['main']['App']['TrashLocalAssets'](arg1);
}

export function UnbindLinuxDoAccount() {
  return window['go']['main']['App']['UnbindLinuxDoAccount']();
}

export function UninstallDesktopStoragePlugin(arg1) {
  return window['go']['main']['App']['UninstallDesktopStoragePlugin'](arg1);
}

export function UninstallDesktopSystemPlugin(arg1) {
  return window['go']['main']['App']['UninstallDesktopSystemPlugin'](arg1);
}

export function UpdateAiConfig(arg1) {
  return window['go']['main']['App']['UpdateAiConfig'](arg1);
}

export function UpdateAlbum(arg1, arg2) {
  return window['go']['main']['App']['UpdateAlbum'](arg1, arg2);
}

export function UpdateBlog(arg1, arg2) {
  return window['go']['main']['App']['UpdateBlog'](arg1, arg2);
}

export function UpdateCommentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateCommentStatus'](arg1, arg2);
}

export function UpdateDesktopStorageSource(arg1) {
  return window['go']['main']['App']['UpdateDesktopStorageSource'](arg1);
}

export function UpdateEditorAiConversation(arg1, arg2) {
  return window['go']['main']['App']['UpdateEditorAiConversation'](arg1, arg2);
}

export function UpdateEditorAiTaskState(arg1) {
  return window['go']['main']['App']['UpdateEditorAiTaskState'](arg1);
}

export function UpdateFilmRoll(arg1, arg2) {
  return window['go']['main']['App']['UpdateFilmRoll'](arg1, arg2);
}

export function UpdateFriend(arg1, arg2) {
  return window['go']['main']['App']['UpdateFriend'](arg1, arg2);
}

export function UpdateLocalAsset(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateLocalAsset'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateLocalLibraryCollection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateLocalLibraryCollection'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateLocalLibraryCollectionGroup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateLocalLibraryCollectionGroup'](arg1, arg2, arg3, arg4);
}

export function UpdateLocalLibraryTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLocalLibraryTag'](arg1, arg2, arg3);
}

export function UpdateLogConfig(arg1) {
  return window['go']['main']['App']['UpdateLogConfig'](arg1);
}

export function UpdatePhoto(arg1, arg2) {
  return window['go']['main']['App']['UpdatePhoto'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateStory(arg1, arg2) {
  return window['go']['main']['App']['UpdateStory'](arg1, arg2);
}

export function UpdateWindowStyle(arg1) {
  return window['go']['main']['App']['UpdateWindowStyle'](arg1);
}

export function UpgradeLocalLibrary(arg1) {
  return window['go']['main']['App']['UpgradeLocalLibrary'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}

export function UploadLocalAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadLocalAsset'](arg1, arg2, arg3, arg4);
}
