// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {types} from '../models';
import {image} from '../models';

export function AddStoryPhoto(arg1:string,arg2:string):Promise<void>;

export function BatchDeletePhotos(arg1:services.BatchDeleteParams):Promise<services.BatchResult>;

export function BatchUpdateShowFlag(arg1:Array<string>,arg2:boolean):Promise<services.BatchResult>;

export function CheckDuplicates(arg1:Array<string>):Promise<services.DuplicateCheckResult>;

export function CreateAlbum(arg1:services.CreateAlbumParams):Promise<services.AlbumDTO>;

export function CreateBlog(arg1:services.CreateBlogParams):Promise<services.BlogDTO>;

export function CreateFilmRoll(arg1:services.CreateFilmRollParams):Promise<services.FilmRollDTO>;

export function CreateFriend(arg1:services.CreateFriendParams):Promise<services.FriendDTO>;

export function CreateStorageSource(arg1:Record<string, string>):Promise<types.StorageSourceDTO>;

export function CreateStory(arg1:services.CreateStoryParams):Promise<services.StoryDTO>;

export function DeleteAlbum(arg1:string):Promise<void>;

export function DeleteBlog(arg1:string):Promise<void>;

export function DeleteComment(arg1:string):Promise<void>;

export function DeleteFilmRoll(arg1:string):Promise<void>;

export function DeleteFriend(arg1:string):Promise<void>;

export function DeletePhoto(arg1:string,arg2:services.DeletePhotoParams):Promise<void>;

export function DeleteStorageSource(arg1:string):Promise<void>;

export function DeleteStory(arg1:string):Promise<void>;

export function GetAlbum(arg1:string):Promise<services.AlbumDTO>;

export function GetAlbums():Promise<Array<services.AlbumDTO>>;

export function GetBlog(arg1:string):Promise<services.BlogDTO>;

export function GetBlogs():Promise<Array<services.BlogDTO>>;

export function GetCategories():Promise<Array<string>>;

export function GetComments(arg1:services.ListCommentsParams):Promise<services.PaginatedResponse_mo_gallery_desktop_services_CommentDTO_>;

export function GetFilmRoll(arg1:string):Promise<services.FilmRollDTO>;

export function GetFilmRolls():Promise<Array<services.FilmRollDTO>>;

export function GetFriends():Promise<Array<services.FriendDTO>>;

export function GetPhoto(arg1:string):Promise<services.PhotoDTO>;

export function GetPhotos(arg1:services.ListPhotosParams):Promise<services.PaginatedResponse_mo_gallery_desktop_services_PhotoDTO_>;

export function GetSettings():Promise<Record<string, string>>;

export function GetStorageSources():Promise<Array<types.StorageSourceDTO>>;

export function GetStories():Promise<Array<services.StoryDTO>>;

export function GetStory(arg1:string):Promise<services.StoryDTO>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<services.LoginResult>;

export function PrepareUpload(arg1:Array<string>):Promise<Array<services.PreparedFile>>;

export function RemoveStoryPhoto(arg1:string,arg2:string):Promise<void>;

export function ReorderStoryPhotos(arg1:string,arg2:Array<string>):Promise<services.StoryDTO>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SetAuth(arg1:string,arg2:string):Promise<void>;

export function ToggleFeatured(arg1:string):Promise<services.PhotoDTO>;

export function ToggleShowFlag(arg1:string):Promise<services.PhotoDTO>;

export function UpdateAlbum(arg1:string,arg2:services.UpdateAlbumParams):Promise<services.AlbumDTO>;

export function UpdateBlog(arg1:string,arg2:services.UpdateBlogParams):Promise<services.BlogDTO>;

export function UpdateCommentStatus(arg1:string,arg2:string):Promise<void>;

export function UpdateFilmRoll(arg1:string,arg2:services.UpdateFilmRollParams):Promise<services.FilmRollDTO>;

export function UpdateFriend(arg1:string,arg2:services.UpdateFriendParams):Promise<services.FriendDTO>;

export function UpdatePhoto(arg1:string,arg2:services.UpdatePhotoParams):Promise<services.PhotoDTO>;

export function UpdateSettings(arg1:Record<string, string>):Promise<Record<string, string>>;

export function UpdateStorageSource(arg1:string,arg2:Record<string, string>):Promise<types.StorageSourceDTO>;

export function UpdateStory(arg1:string,arg2:services.UpdateStoryParams):Promise<services.StoryDTO>;

export function UploadFile(arg1:string,arg2:services.UploadSettings,arg3:string,arg4:image.ExifData):Promise<services.UploadResult>;

export function ValidateToken(arg1:string):Promise<services.UserInfo>;
