// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStoryPhoto(arg1, arg2) {
  return window['go']['main']['App']['AddStoryPhoto'](arg1, arg2);
}

export function BatchDeletePhotos(arg1) {
  return window['go']['main']['App']['BatchDeletePhotos'](arg1);
}

export function BatchUpdateShowFlag(arg1, arg2) {
  return window['go']['main']['App']['BatchUpdateShowFlag'](arg1, arg2);
}

export function CheckDuplicates(arg1) {
  return window['go']['main']['App']['CheckDuplicates'](arg1);
}

export function CreateAlbum(arg1) {
  return window['go']['main']['App']['CreateAlbum'](arg1);
}

export function CreateBlog(arg1) {
  return window['go']['main']['App']['CreateBlog'](arg1);
}

export function CreateFilmRoll(arg1) {
  return window['go']['main']['App']['CreateFilmRoll'](arg1);
}

export function CreateFriend(arg1) {
  return window['go']['main']['App']['CreateFriend'](arg1);
}

export function CreateStorageSource(arg1) {
  return window['go']['main']['App']['CreateStorageSource'](arg1);
}

export function CreateStory(arg1) {
  return window['go']['main']['App']['CreateStory'](arg1);
}

export function DeleteAlbum(arg1) {
  return window['go']['main']['App']['DeleteAlbum'](arg1);
}

export function DeleteBlog(arg1) {
  return window['go']['main']['App']['DeleteBlog'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['App']['DeleteComment'](arg1);
}

export function DeleteFilmRoll(arg1) {
  return window['go']['main']['App']['DeleteFilmRoll'](arg1);
}

export function DeleteFriend(arg1) {
  return window['go']['main']['App']['DeleteFriend'](arg1);
}

export function DeletePhoto(arg1, arg2) {
  return window['go']['main']['App']['DeletePhoto'](arg1, arg2);
}

export function DeleteStorageSource(arg1) {
  return window['go']['main']['App']['DeleteStorageSource'](arg1);
}

export function DeleteStory(arg1) {
  return window['go']['main']['App']['DeleteStory'](arg1);
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetAlbums() {
  return window['go']['main']['App']['GetAlbums']();
}

export function GetBlog(arg1) {
  return window['go']['main']['App']['GetBlog'](arg1);
}

export function GetBlogs() {
  return window['go']['main']['App']['GetBlogs']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetComments(arg1) {
  return window['go']['main']['App']['GetComments'](arg1);
}

export function GetFilmRoll(arg1) {
  return window['go']['main']['App']['GetFilmRoll'](arg1);
}

export function GetFilmRolls() {
  return window['go']['main']['App']['GetFilmRolls']();
}

export function GetFriends() {
  return window['go']['main']['App']['GetFriends']();
}

export function GetPhoto(arg1) {
  return window['go']['main']['App']['GetPhoto'](arg1);
}

export function GetPhotos(arg1) {
  return window['go']['main']['App']['GetPhotos'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStorageSources() {
  return window['go']['main']['App']['GetStorageSources']();
}

export function GetStories() {
  return window['go']['main']['App']['GetStories']();
}

export function GetStory(arg1) {
  return window['go']['main']['App']['GetStory'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function PrepareUpload(arg1) {
  return window['go']['main']['App']['PrepareUpload'](arg1);
}

export function RemoveStoryPhoto(arg1, arg2) {
  return window['go']['main']['App']['RemoveStoryPhoto'](arg1, arg2);
}

export function ReorderStoryPhotos(arg1, arg2) {
  return window['go']['main']['App']['ReorderStoryPhotos'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAuth(arg1, arg2) {
  return window['go']['main']['App']['SetAuth'](arg1, arg2);
}

export function ToggleFeatured(arg1) {
  return window['go']['main']['App']['ToggleFeatured'](arg1);
}

export function ToggleShowFlag(arg1) {
  return window['go']['main']['App']['ToggleShowFlag'](arg1);
}

export function UpdateAlbum(arg1, arg2) {
  return window['go']['main']['App']['UpdateAlbum'](arg1, arg2);
}

export function UpdateBlog(arg1, arg2) {
  return window['go']['main']['App']['UpdateBlog'](arg1, arg2);
}

export function UpdateCommentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateCommentStatus'](arg1, arg2);
}

export function UpdateFilmRoll(arg1, arg2) {
  return window['go']['main']['App']['UpdateFilmRoll'](arg1, arg2);
}

export function UpdateFriend(arg1, arg2) {
  return window['go']['main']['App']['UpdateFriend'](arg1, arg2);
}

export function UpdatePhoto(arg1, arg2) {
  return window['go']['main']['App']['UpdatePhoto'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateStorageSource(arg1, arg2) {
  return window['go']['main']['App']['UpdateStorageSource'](arg1, arg2);
}

export function UpdateStory(arg1, arg2) {
  return window['go']['main']['App']['UpdateStory'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}

export function ValidateToken(arg1) {
  return window['go']['main']['App']['ValidateToken'](arg1);
}
