// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {local_library} from '../models';
import {agent_extensions} from '../models';
import {storage_plugins} from '../models';
import {main} from '../models';
import {config} from '../models';
import {types} from '../models';
import {image} from '../models';

export function AddPhotosToAlbum(arg1:string,arg2:Array<string>):Promise<services.AlbumDTO>;

export function AddPhotosToFilmRoll(arg1:string,arg2:Array<string>):Promise<services.FilmRollDTO>;

export function AddStoryPhoto(arg1:string,arg2:string):Promise<void>;

export function AppendEditorAiMessage(arg1:services.EditorAiMessageAppendInput):Promise<services.EditorAiMessageDTO>;

export function AppendZineLogs(arg1:Array<string>):Promise<void>;

export function BatchDeletePhotos(arg1:services.BatchDeleteParams):Promise<services.BatchResult>;

export function BatchUpdateLocalAssetOrganization(arg1:local_library.BatchAssetOrganizationUpdate):Promise<void>;

export function BatchUpdateLocalAssetOrganizationByQuery(arg1:string,arg2:local_library.BatchAssetOrganizationUpdate):Promise<void>;

export function BatchUpdateShowFlag(arg1:Array<string>,arg2:boolean):Promise<services.BatchResult>;

export function CallAgentMCPTool(arg1:agent_extensions.MCPToolCallInput):Promise<agent_extensions.MCPToolCallResult>;

export function CancelAgentMCPTool(arg1:string):Promise<boolean>;

export function CancelLocalLibraryScan():Promise<void>;

export function CheckCloudDownloadConflict(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function CheckCloudDownloadConflictByFileName(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function CheckDuplicates(arg1:Array<string>):Promise<services.DuplicateCheckResult>;

export function CheckForUpdates(arg1:string,arg2:boolean):Promise<services.UpdateInfo>;

export function CheckLocalLibraryUpgrade(arg1:string):Promise<Record<string, any>>;

export function CleanupStorage(arg1:Array<string>,arg2:string):Promise<services.StorageCleanupResult>;

export function ClearAuth():Promise<void>;

export function ClearEditorAiConversation(arg1:string):Promise<services.EditorAiConversationDTO>;

export function ClearLocalAssetCloudLink(arg1:string):Promise<void>;

export function ClearLocalLibraryPreviewCache():Promise<void>;

export function ClearLogs():Promise<void>;

export function CloseLocalLibrary():Promise<void>;

export function CompleteSetup(arg1:Record<string, any>):Promise<void>;

export function CopyLocalAssetsToClipboard(arg1:Array<string>,arg2:boolean):Promise<void>;

export function CreateAlbum(arg1:services.CreateAlbumParams):Promise<services.AlbumDTO>;

export function CreateBlog(arg1:services.CreateBlogParams):Promise<services.BlogDTO>;

export function CreateDesktopStorageSource(arg1:storage_plugins.SourceInput):Promise<storage_plugins.SourceDTO>;

export function CreateEditorAiConversation(arg1:services.EditorAiConversationCreateInput):Promise<services.EditorAiConversationDTO>;

export function CreateFilmRoll(arg1:services.CreateFilmRollParams):Promise<services.FilmRollDTO>;

export function CreateFriend(arg1:services.CreateFriendParams):Promise<services.FriendDTO>;

export function CreateLocalAssetQueryToken(arg1:local_library.AssetQuery):Promise<local_library.AssetQueryToken>;

export function CreateLocalLibrary(arg1:string,arg2:string):Promise<local_library.LibrarySnapshot>;

export function CreateLocalLibraryBackup():Promise<local_library.BackupInfo>;

export function CreateLocalLibraryCollection(arg1:any,arg2:string,arg3:string):Promise<local_library.CollectionDTO>;

export function CreateLocalLibraryFolder(arg1:string,arg2:string):Promise<local_library.FolderDTO>;

export function CreateLocalLibraryTag(arg1:string,arg2:string):Promise<local_library.TagDTO>;

export function CreateStory(arg1:services.CreateStoryParams):Promise<services.StoryDTO>;

export function DeleteAlbum(arg1:string):Promise<void>;

export function DeleteBlog(arg1:string):Promise<void>;

export function DeleteComment(arg1:string):Promise<void>;

export function DeleteDesktopStorageSource(arg1:string):Promise<void>;

export function DeleteEditorAiConversation(arg1:string):Promise<void>;

export function DeleteFilmRoll(arg1:string):Promise<void>;

export function DeleteFriend(arg1:string):Promise<void>;

export function DeleteLocalAssetCloud(arg1:string,arg2:boolean):Promise<void>;

export function DeleteLocalAssetCloudAndLocal(arg1:string,arg2:boolean):Promise<void>;

export function DeleteLocalDraft(arg1:string):Promise<void>;

export function DeleteLocalLibraryCollection(arg1:string):Promise<void>;

export function DeleteLocalLibraryCollectionGroup(arg1:string,arg2:boolean):Promise<void>;

export function DeleteLocalLibraryFolder(arg1:string):Promise<void>;

export function DeleteLocalLibraryTag(arg1:string):Promise<void>;

export function DeletePhoto(arg1:string,arg2:services.DeletePhotoParams):Promise<void>;

export function DeleteStory(arg1:string):Promise<void>;

export function DeleteZineProject(arg1:string):Promise<void>;

export function DiscoverAgentMCPServerTools(arg1:string):Promise<agent_extensions.MCPServer>;

export function DownloadCloudPhotoToFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadCloudPhotoToLocalLibrary(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<local_library.ImportResult>>;

export function DownloadMessageImageToLocal(arg1:string):Promise<string>;

export function DownloadUpdate():Promise<services.UpdateDownloadResult>;

export function ExecuteLocalAssetMovePlan(arg1:string):Promise<local_library.AssetFileOperationExecution>;

export function ExecuteLocalLibraryFolderMovePlan(arg1:string):Promise<local_library.FolderFileOperationExecution>;

export function FetchURLMetadata(arg1:string):Promise<main.FetchURLMetadataResult>;

export function FinishEditorAiMessage(arg1:services.EditorAiMessageFinishInput):Promise<services.EditorAiMessageDTO>;

export function FixMissingPhotos(arg1:Array<string>):Promise<services.FixMissingPhotosResult>;

export function GenerateThumbnail(arg1:string):Promise<services.PhotoDTO>;

export function GetAgentExtensionSnapshot():Promise<agent_extensions.AgentExtensionSnapshot>;

export function GetAiConfig():Promise<config.AIConfig>;

export function GetAiHttpPort():Promise<number>;

export function GetAiImageDataURL(arg1:string):Promise<string>;

export function GetAlbum(arg1:string):Promise<services.AlbumDTO>;

export function GetAlbums():Promise<Array<services.AlbumDTO>>;

export function GetAllPhotos():Promise<Array<services.PhotoDTO>>;

export function GetApiConfig():Promise<Record<string, any>>;

export function GetBlog(arg1:string):Promise<services.BlogDTO>;

export function GetBlogs():Promise<Array<services.BlogDTO>>;

export function GetCameras():Promise<Array<services.CameraDTO>>;

export function GetCategories():Promise<Array<string>>;

export function GetComments(arg1:services.ListCommentsParams):Promise<services.PaginatedResponse_mo_gallery_desktop_services_CommentDTO_>;

export function GetDesktopPluginMarketplace(arg1:boolean):Promise<storage_plugins.MarketplaceCatalog>;

export function GetDesktopStoragePlugins():Promise<Array<storage_plugins.PluginDescriptor>>;

export function GetDesktopStorageSourceCredentials(arg1:string):Promise<Record<string, string>>;

export function GetDesktopStorageSources():Promise<Array<storage_plugins.SourceDTO>>;

export function GetDesktopSystemPlugins():Promise<Array<storage_plugins.PluginDescriptor>>;

export function GetEditorAiConversation(arg1:string):Promise<services.EditorAiConversationWithMessagesDTO>;

export function GetEditorAiConversationMessagesPage(arg1:string,arg2:string,arg3:string,arg4:number):Promise<services.EditorAiConversationWithMessagesDTO>;

export function GetEditorAiConversationPage(arg1:string,arg2:number,arg3:number):Promise<services.EditorAiConversationPageDTO>;

export function GetEditorAiConversations(arg1:string):Promise<Array<services.EditorAiConversationDTO>>;

export function GetFileThumbnail(arg1:string):Promise<string>;

export function GetFilmRoll(arg1:string):Promise<services.FilmRollDTO>;

export function GetFilmRolls():Promise<Array<services.FilmRollDTO>>;

export function GetFriends():Promise<Array<services.FriendDTO>>;

export function GetLenses():Promise<Array<services.LensDTO>>;

export function GetLinuxDoAuthUrl():Promise<services.LinuxDoAuthUrlDTO>;

export function GetLinuxDoBinding():Promise<services.LinuxDoBindingDTO>;

export function GetLocalAssetOriginalPaths(arg1:Array<string>):Promise<Array<string>>;

export function GetLocalDraft(arg1:string):Promise<string>;

export function GetLocalLibraryBackups():Promise<local_library.BackupOverview>;

export function GetLocalLibraryCacheStats():Promise<local_library.LocalLibraryCacheStats>;

export function GetLocalLibraryEntryState():Promise<Record<string, any>>;

export function GetLocalLibraryFolderProperties(arg1:string):Promise<local_library.FolderProperties>;

export function GetLocalLibraryPreferences():Promise<local_library.LocalLibraryPreferences>;

export function GetLocalLibrarySnapshot():Promise<local_library.LibrarySnapshot>;

export function GetLogConfig():Promise<Record<string, any>>;

export function GetLogDir():Promise<string>;

export function GetLogStats():Promise<Record<string, any>>;

export function GetLogs(arg1:string,arg2:string,arg3:number):Promise<Array<services.LogEntry>>;

export function GetOverview():Promise<services.OverviewDTO>;

export function GetPhoto(arg1:string):Promise<services.PhotoDTO>;

export function GetPhotos(arg1:services.ListPhotosParams):Promise<services.PaginatedResponse_mo_gallery_desktop_services_PhotoDTO_>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSetupState():Promise<Record<string, any>>;

export function GetStorageSources():Promise<Array<types.StorageSourceDTO>>;

export function GetStories():Promise<Array<services.StoryDTO>>;

export function GetStory(arg1:string):Promise<services.StoryDTO>;

export function GetStoryAiModels():Promise<services.StoryAiModelsResponseDTO>;

export function GetStoryAiProviderModels(arg1:string):Promise<services.StoryAiModelsResponseDTO>;

export function GetWindowAppearance():Promise<main.WindowAppearance>;

export function GetZineAssetBlob(arg1:string):Promise<string>;

export function GetZineCJKFontInfo():Promise<services.ZineCJKFontInfo>;

export function GetZineImageDataURL(arg1:string):Promise<string>;

export function GetZineLogPath():Promise<string>;

export function GetZineProject(arg1:string):Promise<string>;

export function GetZineSystemFonts():Promise<Array<string>>;

export function ImportAgentMCPServers(arg1:string):Promise<Array<agent_extensions.MCPServer>>;

export function ImportLocalLibraryFiles(arg1:Array<string>,arg2:string):Promise<Array<local_library.ImportResult>>;

export function InitializeLocalLibrary(arg1:string,arg2:string):Promise<local_library.LibrarySnapshot>;

export function InstallDesktopMarketplacePlugin(arg1:string,arg2:string):Promise<storage_plugins.PluginDescriptor>;

export function InstallDesktopStoragePlugin(arg1:string):Promise<storage_plugins.PluginDescriptor>;

export function InstallDesktopStoragePluginPackage(arg1:string):Promise<storage_plugins.PluginDescriptor>;

export function InstallDesktopSystemPlugin(arg1:string):Promise<storage_plugins.PluginDescriptor>;

export function InstallDesktopSystemPluginPackage(arg1:string):Promise<storage_plugins.PluginDescriptor>;

export function IsLinuxDoEnabled():Promise<boolean>;

export function ListDesktopStorageObjects(arg1:string,arg2:string,arg3:string,arg4:number):Promise<storage_plugins.ListResult>;

export function ListDesktopStoragePluginVersions(arg1:string):Promise<Array<storage_plugins.PluginVersionDescriptor>>;

export function ListDesktopSystemPluginVersions(arg1:string):Promise<Array<storage_plugins.PluginVersionDescriptor>>;

export function ListLocalAssets(arg1:local_library.AssetQuery):Promise<local_library.AssetPage>;

export function ListLocalDrafts():Promise<Array<string>>;

export function ListLocalFolders():Promise<Array<local_library.FolderDTO>>;

export function ListLocalLibraryCollectionGroups():Promise<Array<local_library.CollectionGroupDTO>>;

export function ListLocalLibraryCollections():Promise<Array<local_library.CollectionDTO>>;

export function ListLocalLibraryTags():Promise<Array<local_library.TagDTO>>;

export function ListLocalLibraryTrashedFolders():Promise<Array<local_library.FolderTrashEntry>>;

export function ListZineProjects():Promise<Array<string>>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<services.LoginResult>;

export function MoveDesktopPluginPhotos(arg1:main.MoveDesktopPhotosInput):Promise<services.BatchResult>;

export function MoveLocalAssets(arg1:Array<string>,arg2:string):Promise<Array<local_library.AssetMoveResult>>;

export function MoveLocalLibraryFolder(arg1:string,arg2:string,arg3:string):Promise<local_library.FolderDTO>;

export function OpenDesktopStoragePluginLocation(arg1:string):Promise<void>;

export function OpenDesktopSystemPluginLocation(arg1:string):Promise<void>;

export function OpenDownloadedUpdate():Promise<void>;

export function OpenLocalAssetInDefaultApp(arg1:string):Promise<void>;

export function OpenLocalAssetInFileManager(arg1:string):Promise<void>;

export function OpenLocalLibrary(arg1:string):Promise<local_library.LibrarySnapshot>;

export function OpenLocalLibraryFolderInFileManager(arg1:string):Promise<void>;

export function OpenLogDir():Promise<void>;

export function PauseLocalLibraryScan():Promise<void>;

export function PermanentDeleteActiveLocalLibraryFolder(arg1:string):Promise<void>;

export function PermanentDeleteLocalAssets(arg1:Array<string>):Promise<Array<local_library.TrashResult>>;

export function PermanentDeleteLocalLibraryFolder(arg1:string):Promise<void>;

export function PlanLocalAssetMove(arg1:Array<string>,arg2:string,arg3:string):Promise<local_library.AssetFileOperationPlan>;

export function PlanLocalLibraryFolderMove(arg1:string,arg2:string,arg3:string,arg4:string):Promise<local_library.FolderFileOperationPlan>;

export function PrepareClipboardUpload(arg1:Array<string>,arg2:Array<string>):Promise<Array<services.PreparedFile>>;

export function PrepareLocalAssetUpload(arg1:Array<string>):Promise<Array<services.PreparedFile>>;

export function PrepareUpload(arg1:Array<string>):Promise<Array<services.PreparedFile>>;

export function PreviewLocalLibraryFolderDeletion(arg1:string):Promise<local_library.FolderDeletionPreview>;

export function ReadAgentSkill(arg1:string):Promise<agent_extensions.SkillContent>;

export function ReadAgentSkillResource(arg1:string,arg2:string):Promise<agent_extensions.SkillResource>;

export function RecheckMissingLocalAssets(arg1:Array<string>):Promise<Array<local_library.AssetMaintenanceResult>>;

export function RemoveAgentMCPServer(arg1:string):Promise<void>;

export function RemoveAgentSkill(arg1:string):Promise<void>;

export function RemoveMissingLocalAssets(arg1:Array<string>):Promise<Array<local_library.AssetMaintenanceResult>>;

export function RemovePhotoFromAlbum(arg1:string,arg2:string):Promise<services.AlbumDTO>;

export function RemovePhotoFromFilmRoll(arg1:string,arg2:string):Promise<services.FilmRollDTO>;

export function RemoveRecentLocalLibrary(arg1:string):Promise<void>;

export function RemoveStoryPhoto(arg1:string,arg2:string):Promise<void>;

export function RenameLocalAsset(arg1:string,arg2:string):Promise<local_library.AssetMoveResult>;

export function ReorderFilmRollFrames(arg1:string):Promise<services.FilmRollDTO>;

export function ReorderFriends(arg1:Array<services.ReorderFriendItem>):Promise<void>;

export function ReorderStoryPhotos(arg1:string,arg2:Array<string>):Promise<services.StoryDTO>;

export function RestartApplication():Promise<void>;

export function RestoreLocalAsset(arg1:string):Promise<void>;

export function RestoreLocalLibraryBackup(arg1:string):Promise<local_library.LibrarySnapshot>;

export function RestoreLocalLibraryFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResumeLocalLibraryScan():Promise<void>;

export function RetryLocalAssetPreviews(arg1:Array<string>):Promise<Array<local_library.AssetMaintenanceResult>>;

export function RevokeAgentAuthorization(arg1:string):Promise<void>;

export function RollbackDesktopStoragePlugin(arg1:string,arg2:string):Promise<void>;

export function RollbackDesktopSystemPlugin(arg1:string,arg2:string):Promise<void>;

export function SaveAgentMCPServer(arg1:agent_extensions.MCPServerInput):Promise<agent_extensions.MCPServer>;

export function SaveAiImageToAlbum(arg1:string):Promise<services.PhotoDTO>;

export function SaveLocalDraft(arg1:string,arg2:string):Promise<void>;

export function SaveMessageImageToAlbum(arg1:string,arg2:string):Promise<services.PhotoDTO>;

export function SaveMessageImageToLocalLibrary(arg1:string,arg2:string):Promise<Array<local_library.ImportResult>>;

export function SaveZineAssetBlob(arg1:string,arg2:string):Promise<void>;

export function SaveZineProject(arg1:string):Promise<void>;

export function ScanStorage(arg1:services.StorageScanParams):Promise<services.StorageScanResult>;

export function SelectAndImportSkillArchive():Promise<Array<agent_extensions.Skill>>;

export function SelectAndImportSkillDirectory():Promise<Array<agent_extensions.Skill>>;

export function SelectDesktopStoragePluginManifest():Promise<string>;

export function SelectDesktopStoragePluginPackage():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SelectLocalLibraryFolder(arg1:string):Promise<string>;

export function SelectLocalLibraryImportFiles():Promise<Array<string>>;

export function SetAgentMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAgentSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAgentSkillScriptExecution(arg1:string,arg2:boolean):Promise<void>;

export function SetAlbumCover(arg1:string,arg2:string):Promise<services.AlbumDTO>;

export function SetAuth(arg1:string,arg2:string):Promise<services.UserInfo>;

export function SetDesktopStorageSourceEnabled(arg1:string,arg2:boolean):Promise<storage_plugins.SourceDTO>;

export function SetFilmRollFrameOrder(arg1:string,arg2:Array<string>):Promise<services.FilmRollDTO>;

export function SetLocalAssetCloudLink(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetLocalAssetCollections(arg1:string,arg2:Array<string>):Promise<void>;

export function SetLocalAssetTags(arg1:string,arg2:Array<string>):Promise<void>;

export function SetLocalLibraryImportMode(arg1:string):Promise<local_library.LocalLibraryPreferences>;

export function StartLocalLibraryScan():Promise<void>;

export function SyncLocalLibraryCloud():Promise<local_library.CloudSyncStatus>;

export function TestAgentMCPServer(arg1:string):Promise<agent_extensions.MCPServer>;

export function TestDesktopStorageSource(arg1:string):Promise<storage_plugins.HealthResult>;

export function ToggleFeatured(arg1:string):Promise<services.PhotoDTO>;

export function ToggleShowFlag(arg1:string):Promise<services.PhotoDTO>;

export function TrashLocalAssets(arg1:Array<string>):Promise<Array<local_library.TrashResult>>;

export function UnbindLinuxDoAccount():Promise<void>;

export function UninstallDesktopStoragePlugin(arg1:string):Promise<void>;

export function UninstallDesktopSystemPlugin(arg1:string):Promise<void>;

export function UpdateAiConfig(arg1:config.AIConfig):Promise<void>;

export function UpdateAlbum(arg1:string,arg2:services.UpdateAlbumParams):Promise<services.AlbumDTO>;

export function UpdateBlog(arg1:string,arg2:services.UpdateBlogParams):Promise<services.BlogDTO>;

export function UpdateCommentStatus(arg1:string,arg2:string):Promise<void>;

export function UpdateDesktopStorageSource(arg1:storage_plugins.SourceInput):Promise<storage_plugins.SourceDTO>;

export function UpdateEditorAiConversation(arg1:string,arg2:services.EditorAiConversationUpdateInput):Promise<services.EditorAiConversationDTO>;

export function UpdateEditorAiTaskState(arg1:services.EditorAiTaskStateUpdateInput):Promise<services.EditorAiMessageDTO>;

export function UpdateFilmRoll(arg1:string,arg2:services.UpdateFilmRollParams):Promise<services.FilmRollDTO>;

export function UpdateFriend(arg1:string,arg2:services.UpdateFriendParams):Promise<services.FriendDTO>;

export function UpdateLocalAsset(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:boolean):Promise<void>;

export function UpdateLocalLibraryCollection(arg1:string,arg2:any,arg3:string,arg4:string,arg5:number):Promise<local_library.CollectionDTO>;

export function UpdateLocalLibraryCollectionGroup(arg1:string,arg2:any,arg3:string,arg4:number):Promise<local_library.CollectionGroupDTO>;

export function UpdateLocalLibraryTag(arg1:string,arg2:string,arg3:string):Promise<local_library.TagDTO>;

export function UpdateLogConfig(arg1:Record<string, any>):Promise<void>;

export function UpdatePhoto(arg1:string,arg2:services.UpdatePhotoParams):Promise<services.PhotoDTO>;

export function UpdateSettings(arg1:Record<string, string>):Promise<Record<string, string>>;

export function UpdateStory(arg1:string,arg2:services.UpdateStoryParams):Promise<services.StoryDTO>;

export function UpdateWindowStyle(arg1:string):Promise<main.WindowAppearance>;

export function UpgradeLocalLibrary(arg1:string):Promise<Record<string, any>>;

export function UploadFile(arg1:string,arg2:services.UploadSettings,arg3:string,arg4:image.ExifData):Promise<services.UploadResult>;

export function UploadLocalAsset(arg1:string,arg2:services.UploadSettings,arg3:string,arg4:image.ExifData):Promise<services.UploadResult>;
